[package]
name = "readline"
version = "0.1.0"
authors = ["Sean Perry", "Mika Attila"]
build = "build.rs"
description = "Simple wrapper around libreadline or libedit"
repository = "https://github.com/shaleh/rust-readline"

[dependencies]
libc = "*"
